###
GET http://localhost:8080/dashboard
Accept: application/json

### Add new dashboard
POST http://localhost:8080/dashboard/new
Accept: application/json
Content-Type: application/json

{
  "name": "Dashboard Name",
  "active": 1,
  "idUser": 1
}

### Get list of dashboards by user id
GET http://localhost:8080/dashboard/1/list
Accept: application/json


### Update dashboard by user id
PATCH http://localhost:8080/dashboard/user/1
Accept: application/json
Content-Type: application/json

{
  "idDashboard": 1,
  "name": "Dashboard"
}