###
GET http://localhost:8080/dashboard
Accept: application/json

### Add new dashboard
POST http://localhost:8080/dashboard/new
Accept: application/json
Content-Type: application/json

{
  "name": "Dashboard Name",
  "active": 1,
  "idUser": 1,
  "txUserId": 1,
  "txHost": "127.0.0.1",
  "txDate": "2021-05-26"
}

### Get list of dashboards by user id
GET http://localhost:8080/dashboard/1/list
Accept: application/json


### Update dashboard by dashboard id and user id
PATCH http://localhost:8080/dashboard/1/user/1
Accept: application/json
Content-Type: application/json

{
  "name": "Dashboard Name"
}