### Add new data
POST http://localhost:8080/data/new/single
Accept: application/json
Content-Type: application/json
#Authorization:

{
  "department": "La Paz",
  "municipality": "All",
  "inDate": "2021-12-31T16:00:00Z",
  "confirmed": 100,
  "deaths": 100,
  "recovered": 100,
  "actives": 100,
  "firstDose": 100,
  "secondDose": 100
}

### Last data by location id
GET http://localhost:8080/data/last/day/29
Accept: application/json
Content-Type: application/json

### Get general data by Country ID
GET http://localhost:8080/data/general/29
Accept: application/json

### Get general data list by Country ID
GET http://localhost:8080/data/general/list/29
Accept: application/json
