GET http://localhost:8080/data/department/1
Accept: application/json
Content-Type: application/json

### Add new data
POST http://localhost:8080/data/new/single
Accept: application/json
Content-Type: application/json

{
  "department": "La Paz",
  "municipality": "default",
  "date": "2021-12-31T16:00:00Z",
  "confirmed": 100,
  "deaths": 100,
  "recovered": 100,
  "actives": null,
  "vaccinated": 100
}

###
GET http://localhost:8080/data/departments/
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/data/departmentgeneral/1
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/data/Bolivia
Accept: application/json
Content-Type: application/json