###
GET https://localhost:8080/actuator/
Accept: application/json

###
GET https://localhost:8080/actuator/health/
Accept: application/json

###
GET https://localhost:8080/actuator/info/
Accept: application/json