POST http://localhost:8080/person/
Accept: application/json
Content-Type: application/json

{
  "nicknameUser":"DaniXd",
  "name":"Daniel",
  "secondName":"Alberto",
  "lastName":"Salazar",
  "secondLastName":"Dominguez",
  "email":"dani@gmail.com",
  "password":"123"
}