POST http://localhost:8080/person/
Accept: application/json
Content-Type: application/json

{
  "nickname": "qwerty1234",
  "firstName": "Zi",
  "secondName": "Alberto",
  "firstLastName": "Salazar",
  "secondLastName": "Dominguez",
  "email": "algo@gmail.com",
  "password": "123",
  "urlPhoto": "https://YonoSe/AlgunaFoto/EnUnaURL"
}
